name: Update Spotify Activity with Streaming

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch Spotify Access Token
      - name: Fetch Spotify Access Token
        id: spotify-auth
        run: |
          response=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=refresh_token" \
            -d "refresh_token=${{ secrets.SPOTIFY_REFRESH_TOKEN }}" \
            -u "${{ secrets.SPOTIFY_CLIENT_ID }}:${{ secrets.SPOTIFY_CLIENT_SECRET }}" \
            https://accounts.spotify.com/api/token)
          echo "token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      # Step 3: Fetch Currently Playing Track
      - name: Fetch Currently Playing Data
        id: fetch-data
        run: |
          track_id=$(curl -s -X GET "https://api.spotify.com/v1/me/player/currently-playing" \
            -H "Authorization: Bearer $token" | jq -r '.item.id')

          if [ $? -ne 0 ]; then
            echo "Error: Failed to retrieve or parse currently playing data from Spotify API." >&2
            echo "track_embed=null" >> $GITHUB_ENV
          else
            if [ "$track_id" != "null" ]; then
              echo "track_embed=https://open.spotify.com/embed/track/$track_id" >> $GITHUB_ENV
            else
              echo "track_embed=null" >> $GITHUB_ENV
            fi
          fi

      # Step 4: Update README
      - name: Update README
        run: |
          if [ "${{ env.track_embed }}" != "null" ]; then
            echo "<iframe src=\"${{ env.track_embed }}\" width=\"300\" height=\"80\" frameborder=\"0\" allowtransparency=\"true\" allow=\"encrypted-media\"></iframe>" > spotify-widget.html
          else
            echo "🎵 Currently listening to: Nothing right now!" > spotify-widget.html
          fi

          # Replace placeholder in README
          sed -i '/<!-- SPOTIFY -->/r spotify-widget.html' README.md

      # Step 5: Commit Changes
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Update Spotify activity"
          git push

