name: Update commit snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#0abfff
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#7723DF&color_dots=#081C30,#10375D,#1C68B5,#2295D1,#0ABFFF

      - name: push to media branch
        run: |
          cd dist
          git init
          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: update contribution snake"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:media
